### PR TITLE
Bump Bevy version to 0.13

### PR DESCRIPTION
**Pull request by Leinnan**
No more, no less. Looks like this version didn't need additional changes :)

### CODE REVIEW

**Review by johanhelsing — APPROVED** [review]
Thanks!

**Comment by honungsburk** [comment]
Are these changes available? I'm using version what I think is the latest release, `0.9.1` of `bevy_pkv`, and I'm not able to migrate to bevy 0.13.

**Comment by johanhelsing** [comment]
@honungsburk sorry, I completely forgot to do the release. Thanks for the reminder. 0.10 is out now.

**Comment by honungsburk** [comment]
@ohanhelsing no worries mate! You've made a great little plugin 😀

**Pull request merged**
