### PR TITLE
Bump version for bevy-0.12

### PR DESCRIPTION
**Pull request by TristanCacqueray**

### CODE REVIEW

**Comment by TristanCacqueray** [comment]
Hello, that appears to work, I'll update the bevy version once it is released.

**Comment by johanhelsing** [comment]
Thanks! Really excited for the new release :)

**Comment by TristanCacqueray** [comment]
You're welcome. The new release should be available anytime soon, and I have been using bevy_pkv with bevy HEAD without any issues.

Thank you for making this lib, it works great!

**Comment by v-kat** [comment]
Do you think you'll be able to release this today? :crossed_fingers:

**Comment by johanhelsing** [comment]
> Do you think you'll be able to release this today? 🤞

Done :)

**Pull request merged**
